<!doctype html>
<html lang="<?php echo app('translator')->locale(); ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CharityRun: <?php echo trans('static.help'); ?></title>
    <base href="<?php echo base_url(); ?>">
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
<div class="layout-container">
    <div class="layout-content">
        <div class="layout-header">
            <?php echo trans('static.help'); ?>
        </div>
        <ul class="help">
            <li class="help-item">
                <input type="checkbox" class="accordion-status help-status" checked>
                <div class="help-title">Help Item</div>
                <p class="help-info accordion-content">Help line</p>
            </li>
            <li class="help-item">
                <input type="checkbox" class="accordion-status help-status" checked>
                <div class="help-title">Help Item 2</div>
                <p class="help-info accordion-content">Help line</p>
            </li>
        </ul>
    </div>
    <nav class="nav">
        <?php
        // try to get the last page
        $referrer = app('request')->getHeader('HTTP_REFERER');

        // if it worked show a back link, else link to the "select class" page
        if(isset($referrer[0])) {
            $back_url = $referrer[0];
            $link_text = 'static.back';
        } else {
            $back_url = '/manage';
            $link_text = 'static.select_class';
        }
        ?>
        <a href="<?php echo $back_url; ?>" class="nav-item"><?php echo trans($link_text); ?></a>
    </nav>
</div>
</body>
</html>