<?php
    // get all available classes
    $classes = \App\Representatives\Classes::getAllNames();
?>
<!doctype html>
<html lang="<?php echo app('translator')->locale(); ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CharityRun: <?php echo trans('static.select_class'); ?></title>
    <base href="<?php echo base_url(); ?>">
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
<div class="layout-container">
    <div class="layout-content">
        <div class="layout-header">
            <?php echo trans('static.select_class'); ?>
        </div>
        <form action="/manage" method="post">
            <?php
            foreach ($classes as $class) {
                $className = $class['name'];
                echo "
                <div class='selector-option'>
                    <input type='radio' name='class' value='$className' id='class$className' class='selector-option-radio'>
                    <label for='class$className' class='selector-option-label'>$className</label>
                </div>
                ";
            }
            ?>
            <input type="submit" class="hidden" id="formSubmit">
        </form>
    </div>
    <div class="selector-footer">
        <label for="formSubmit" class="button button-noBorder selector-submit"><?php echo trans('static.next'); ?></label>
    </div>
</div>
</body>
</html>