<!doctype html>
<html lang="<?php echo app('translator')->locale(); ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CharityRun: <?php echo trans('static.home'); ?></title>
    <base href="<?php echo base_url(); ?>">
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
<div class="layout-container">
    <div class="layout-content">
        <div class="layout-header">
            <?php echo trans('static.select_class'); ?>
        </div>
        <form action="/manage" method="post">
            <div class="selector-option">
                <input type="radio" name="class" value="00" class="hidden" id="class00">
                <label for="class00" class="selector-option-label">00</label>
            </div>
            <div class="selector-option">
                <input type="radio" name="class" value="01" class="hidden" id="class01">
                <label for="class01" class="selector-option-label">01</label>
            </div>
            <div class="selector-option">
                <input type="radio" name="class" value="02" class="hidden" id="class02">
                <label for="class02" class="selector-option-label">02</label>
            </div>
            <div class="selector-option">
                <input type="radio" name="class" value="03" class="hidden" id="class03">
                <label for="class03" class="selector-option-label">03</label>
            </div>
            <input type="submit" class="hidden" id="formSubmit">
        </form>
    </div>
    <div class="selector-footer">
        <label for="formSubmit" class="button button-noBorder selector-submit"><?php echo trans('static.next'); ?></label>
    </div>
</div>
</body>
</html>