<?php /** @var string $class */ ?>
<!doctype html>
<html lang="<?php echo app('translator')->locale(); ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <base href="<?php echo base_url(); ?>">
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
<?php
/**
 * @var \Slim\Views\PhpRenderer $this
 */
echo $this->fetch('module/sidebar.phtml', ['class' => $class, 'isOpen' => true, 'includeJS' => false]);
?>
</body>
</html>