<?php
/** @var string $class */
/** @var int $page */
/** @var array $logs */
?>
<!doctype html>
<html lang="<?php echo app('translator')->getLocale(); ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CharityRun: <?php echo trans('dynamic.log_class_x', ['class' => $class]); ?></title>
    <base href="<?php echo base_url(); ?>">
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
<div class="layout-container">
    <div class="layout-content">
        <div class="layout-header">
            <?php echo trans('dynamic.log_class_x', ['class' => $class]); ?>
        </div>
	    <?php
	    foreach($logs as $log) { ?>
        <form class="log-item" action="/manage/<?php echo $class; ?>/log" method="post">
            <div class="log-item-desc">
                <div class="log-item-type">
                    <span><?php if($log['rounds_changed'] > 0) echo trans('static.added_rounds'); else echo trans('static.rolled_back'); ?></span><span class="log-time"><?php echo $log['datetime']; ?></span>
                </div> <?php echo $log['rounds_changed']; ?> rounds
            </div>
            <input type="hidden" name="id" value="<?php echo $log['id']; ?>">
            <button type="submit" href="<?php if(app('auth')->can('rollback') && $log['active']) echo 'log-item-undo-hasPermission'; ?>" class="log-item-undo <?php if(app('auth')->can('rollback') && $log['active']) echo 'log-item-undo-hasPermission'; ?>">
                <svg class="log-undo-icon"><use xlink:href="/images/undo.svg#icon"></use><image src="images/undo.png" height="24px" width="24px"/></svg>
            </button>
        </form>
        <?php
        }
	    echo '<div class="button-container">';
	    if($page > 1) {
		    $previous_page = $page - 1;
		    echo '<a class="button button-noBorder" href="/manage/'.$class.'/log/'.$previous_page.'"> < Page '.$previous_page.'</a>';
	    }
	    if(count($logs) == 25) {
		    $next_page = $page + 1;
		    echo '<a class="button button-noBorder" href="/manage/'.$class.'/log/'.$next_page.'">Page '.$next_page.' ></a>';
	    }
	    echo '</div>';
	    ?>
    </div>
    <div class="nav"><!--
        --><a href="/manage/<?php echo $class; ?>" class="nav-item"><?php echo trans('static.overview'); ?></a><a href="/manage/<?php echo $class; ?>/add" class="nav-item"><?php echo trans('static.add'); ?></a><a href="/manage/<?php echo $class; ?>/more" class="nav-item" id="more"><?php echo trans('static.more'); ?></a><!--
    --></div>
</div>
<?php
echo $this->fetch('module/sidebar.phtml', ['class' => $class]);
?>
</body>
</html>