<!doctype html>
<html lang="<?php echo app('translator')->locale(); ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CharityRun: <?php echo trans('dynamic.edit_runner_x', ['name' => 'Gunther Gutberg']); ?></title>
    <base href="<?php echo base_url(); ?>">
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
<div class="layout-container">
    <div class="layout-content">
        <div class="layout-header">
            <?php echo trans('dynamic.edit_runner_x', ['name' => 'Gunther Gutberg']); ?>
        </div>
        <form action="/edit/runner/<?php echo $id; ?>" method="post" class="manage-form">
            <label class="manage-row">
                <span><?php echo trans('static.name'); ?>:</span>
                <input type="text" class="manage-list-right edit-input" value="Gunther Gutberg">
            </label>
            <label class="manage-row">
                <span><?php echo trans('static.class'); ?>:</span>
                <select name="class" id="class" class="manage-list-right edit-input">
                    <option value="00" selected>00</option>
                    <option value="01">01</option>
                    <option value="02">02</option>
                    <option value="03">03</option>
                </select>
            </label>
            <div class="manage-row">
                <span><?php echo trans('static.donors'); ?>:</span>
                <div class="button button-noBorder manage-list-right edit-link"><?php echo trans('static.display_donors'); ?></div>
            </div>
            <input type="submit" id="save" class="hidden">
        </form>
        <form action="/edit/runner/<?php echo $id; ?>" method="post" class="manage-form">
            <input type="checkbox" class="hidden" name="doDelete" checked>
            <input type="submit" class="button button-abort" value="<?php echo trans('static.delete'); ?>">
        </form>
    </div>
    <div class="button-container">
        <!-- TODO: Return to runner's class -->
        <a href="/manage" class="button button-back"><?php echo trans('static.cancel'); ?></a>
        <label for="save" class="button button-success"><?php echo trans('static.save'); ?></label>
    </div>
</div>
</body>
</html>